### PR TITLE
Jekyll-ify the site

### PR DESCRIPTION
**Pull request by alexlenail**
Instead of writing html documents, think in terms of data and templates. Updating the site with new events means just updating the data. Updating the way it all looks is updating the templates. 

See https://jekyllrb.com/ and https://jekyllrb.com/tutorials/convert-site-to-jekyll/

### CODE REVIEW

**Comment by edwardloveall** [comment]
Thanks for the PR @zfrenchee!

When I built the site, I thought about using a static site generator and chose not to. Maybe it's time we switch over to one, but I want to talk a little about why I didn't choose one from the start.

Briefly the goal was to make it so there was nothing to install. I assume everyone has a web browser and a text editor, even if that text editor is the github website editor. This made it so there was never any dependencies to update, nothing to install, nothing to debug, etc.

This is obviously at the cost of some potential dynamic features or ease of updating. If we ever needed more dynamism, or updating became too difficult, then this strategy falls flat. I see you added the Sara Hendren event, so maybe it's _already_ is too hard to update! 😬

So that was my rational and I'd love to hear what you think about it.

Also, I like Jekyll and think it's one of a few good choices. Did you consider any alternatives? [Hugo](https://gohugo.io) may be better for cross-platform needs since the organizers have a pretty diverse set of operating systems. Ruby can be a pain if you don't develop in it all day. There's also [Middleman](https://middlemanapp.com) which is back to Ruby, but has a nicer view layer, IMO.

---

Like I said, this may be 100% the right choice, but I wanted to give my rationale incase the upsides still outweigh the downsides.

@adamribaudo, as you do most of the maintenance on the site (I think) care to chime in?

**Comment by adamribaudo** [comment]
The static website is getting pretty unwieldy so yes, something more dynamic is needed.

I'm ok running with @zfrenchee 's recommendation given that he's around to help. Am I understanding correctly that I'd need to install Ruby to build the site moving forward and then push the static built files to make website edits? Or can I simply make edits to the .yml files and some other process builds the site? Grabbing lunch w/ Alex next week and can cover this then.

**Comment by edwardloveall** [comment]
I think you'd probably want to have ruby installed, yea. It's possible to set up some kind of auto build on deploy, but for previewing sake it might just be nicer to you to be able to run it locally

**Comment by alexlenail** [comment]
Thanks for those comments @edwardloveall. 

The reason I chose jekyll is because it was developed by github and it's hard-wired into github pages (https://jekyllrb.com/docs/github-pages/). Hugo, despite being faster and slightly more robust, is not integrated with github, so you would need to do the build locally then push. Here, you don't even need to push the resulting files -- github does that behind the scene for your github pages.

**Comment by alexlenail** [comment]
@adamribaudo if you have ruby installed, go to the `website`  directory and: 
```
gem install jekyll bundler
bundle exec jekyll serve
```
should serve your current working copy of the site on `localhost:4000`. It auto-updates too which is nice.

**Pull request merged**
